### ISSUE TITLE
Can‘t connect with liveprof2

### ISSUE THREAD

**Issue by MeandtheDevilknockingonyourdoor** [bitfocus/companion-module-audiostrom-liveprofessor#1]
Hi,

i have a issue what Happens after upgrade my Mac to big sur.
when I start the instance the log says

“Error: bind EADDRINUSE 127.0.0.1:8011”

Companion Control in live Prof is in standard mode

I don’t know what’s happen. Before the upgrade everything work well.

thx best

**Comment by Julusian** [comment]
For the module maintainer:
It looks like you are using a hardcoded local port for osc, which is guaranteed to fail if trying to use two instances of the module.

You should either:
1) let the osc lib choose a random port for you. This is only useful if you dont have to specify this port inside of the liveprof software.
2) let the user specify the port in the config so that they can change it if running multiple instances or if there is another collision (and a note to help them understand when to change it)

**Comment by audiostrom** [comment]
This should be resolved in the latest commit
